#!/usr/bin/env sh

APP="emage"

BUILD_HOST="emage.run"
BUILD_USER="doodloo"
BUILD_AT="/tmp/edeliver/$APP/builds"

DELIVER_TO="/home/doodloo"

STAGING_HOSTS="emage.run"
STAGING_USER="doodloo"

PRODUCTION_HOSTS=$STAGING__HOSTS
PRODUCTION_USER=$STAGING__USER

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/doodloo/emage_prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/apps/emage_web/config/prod.secret.exs'
    "
  fi
}

pre_erlang_clean_compile() {
  status "Installing NPM dependencies"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd "$BUILD_AT/apps/emage_web/assets"
    yarn install $SILENCE
  "

  status "Building static files"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd "$BUILD_AT/apps/emage_web/assets"
    mkdir -p priv/static
    yarn run deploy $SILENCE
  "

  status "Running phoenix.digest"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd '$BUILD_AT'
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
  "
}
